config/routes.rb
Rails.application.routes.draw do
  
  root 'home#home'

  get 'course/conceptual_physics'

  get 'course/algebra_based_physics'

  get 'course/calculus_based_physics'

  get 'course/calculus'

  get 'course/computer_science'

  get 'about/standards'

  get 'about/bio'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def standards
  end

  def bio
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
  def conceptual_physics
  end

  def algebra_based_physics
  end

  def calculus_based_physics
  end

  def calculus
  end

  def computer_science
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/bio.html.erb
<div class="bio jumbotron">
  <%= image_tag("scwoolf.jpg", width: 225, height: 300, class: "inline_block") %>
  <div class="inline_block bio_text">
  <p>I'm a STEM educator in Fresno, California.</p>
  <p>I primarily teach physical science, mathematics, and computer science, but my range of interests is very broad, and I enjoy helping students in any subject.</p>
  <p>My instruction is very visual, and I illustrate all of my lectures.</p>
  
  </div>
</div>

app/views/about/standards.html.erb
<div class="standards jumbotron">
  <h2 class="display-4">Common Core: Mathematical Practice Standards</h2>
  <li>Making sense of problems and persevere in solving them</li>
  <li>Reason abstractly and quantitatively</li>
  <li>Construct viable arguments and critique the reasoning of others</li>
  <li>Model with mathematics</li>
  <li>Use appropriate tools strategically</li>
  <li>Attend to precision</li>
  <li>Look for and makue use of structure</li>
  <li>Look for and express regularity in repeated reasoning</li>
  <hr class="my-4">
  <h2 class="display-4">Next Generation Science Standards: Science & Engineering Practices</h2>
  <li>Asking questions and defining problems</li>
  <li>Developing and using models</li>
  <li>Planning and carrying out investigations</li>
  <li>Analyzing and interpreting data</li>
  <li>Using mathematics and computational thinking</li>
  <li>Constructing explanations and designing solutions</li>
  <li>Engaging in argument from evidence</li>
  <li>Obtaining, evaluating, and communicating information</li>
  <hr class="my-4">
  <h2 class="display-4">California Computer Science Standards: Core Practices (Pending)</h2>
  <li>Fostering an inclusive computing culture</li>
  <li>Collaborating around computing</li>
  <li>Recognizing and defining computational problems</li>
  <li>Developing and using abstractions</li>
  <li>Creating computational artifacts</li>
  <li>Testing and refining computational artifacts</li>
  <li>Communicating about computing</li>
</div>

app/views/course/algebra_based_physics.html.erb
<div class="algebra_based_physics jumbotron">
  <h2 class="display-4">Algebra-Based Physics</h2>
  <p class="lead">Traditional physics course, covering mechanics, gravitation, thermodynamics, and electromagnetism. Applications to engineering and technology are discussed, and some historical context is introduced. There is a dual emphasis on algebraic problem-solving and building strong physics intuition. Lectures are illustrated.</p>
  <hr class="my-4">
  <p><strong>Prerequisites:</strong> Algebra, essential trigonometry (sines, cosines, tangents)</p>
  <a class="btn btn-success btn-lg" href="#" role="button">Course Website</a>
</div>

app/views/course/calculus.html.erb
<div class="calculus jumbotron">
  <h2 class="display-4">Calculus</h2>
  <p class="lead">Introductory course in differential and integral calculus. Applications from the natural and social sciences are studied extensively. Time permitting, differential equations are introduced.</p>
  <hr class="my-4">
  <p><strong>Prerequisites:</strong> Algebra 2, Trigonometry</p>
  <a class="btn btn-success btn-lg" href="#" role="button">Course Website</a>
</div>

app/views/course/calculus_based_physics.html.erb
<div class="algebra_based_physics jumbotron">
  <h2 class="display-4">Calculus-Based Physics</h2>
  <p class="lead">College physics course, covering mechanics, electromagnetism, and modern physics. The primary aim of this course is to develop a strong intuition for calculus. Time permitting, basic programming in Python will be introduced.</p>
  <hr class="my-4">
  <p><strong>Prerequisites:</strong> Algebra 2, Trigonometry. Must be enrolled in calculus or higher.</p>
  <a class="btn btn-success btn-lg" href="#" role="button">Course Website</a>
</div>

app/views/course/computer_science.html.erb
<div class="computer_science jumbotron">
  <h2 class="display-4">Computer Science</h2>
  <p class="lead">Introductory computer science course, using the Processing visualization library. The first semester is taught primarily in Python; the second, in Javascript. Time permitting, robotic programming in Arduino will be introduced.</p>
  <hr class="my-4">
  <p><strong>Prerequisites:</strong> Algebra. Trigonometry is <strong>strongly</strong> recommended.</p>
  <a class="btn btn-success btn-lg" href="#" role="button">Course Website</a>
</div>

app/views/course/conceptual_physics.html.erb
<div class="conceptual_physics jumbotron">
  <h2 class="display-4">Conceptual Physics</h2>
  <p class="lead">Introductory physics course, covering basic ideas from physics (mass, heat, etc.) and their applications in engineering and technology. There is a strong visual emphasis in both the instruction and coursework. While the course aims for conceptual understanding, it is <strong>not</strong> math-free.</p>
  <hr class="my-4">
  <p><strong>Prerequisites:</strong> Basic arithmetic, up to fractions and exponents. Algebra is strongly recommended. An introductory math unit precedes physics instruction.</p>
  <a class="btn btn-success btn-lg" href="#" role="button">Course Website</a>
</div>

app/views/home/home.html.erb
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/p5.js"></script>
    <script type="text/javascript">
      
      
function setup(){
  let myCanvas = createCanvas(1320,700);
  myCanvas.parent('myContainer');
  background(0);
  let t1 = new Tree(window.innerWidth/2,window.innerHeight+100,90,64);
  t1.display();
}

function draw() {
}

class Tree {

  constructor(xi, yi, angle, thickness){
    this.x = xi;
    this.y = yi;
    this.theta = angle;
    this.thick = thickness;
  }
  
  display(){
    let diminisher = 0.925;
    let threshold = pow(2,floor(log(this.thick)/log(2)));
    while (this.thick > 1){ 
        if (random(0,threshold) > this.thick){
        let num = branch_number(this.thick);
        let a_and_t = angles_and_thicknesses(num,this.theta,this.thick);
        for (let i = 0; i < num; i++){
          let t = new Tree(this.x,this.y,a_and_t[2*i],a_and_t[2*i+1]);
          t.display();
        }  
        break;
      }
      this.theta = angle_prob(this.theta);
      this.x += cos(angle_convert(this.theta));
      this.y += sin(angle_convert(this.theta));
      if (random(0,100) > 95){
        this.thick *= diminisher;
      }
      noStroke();
      fill(210,180,140);
      ellipse(this.x-1,this.y,this.thick,this.thick);
      fill(255,235,205);
      ellipse(this.x,this.y,this.thick,this.thick); 
    }
    if (this.thick <= 1){
    let number_of_blossoms = random(3,10);
    for (let i = 0; i < number_of_blossoms; i++){
      let dx = random(-25,25);
      let dy = random(-25,25);
      noFill();
      stroke(130,130,30);
      bezier(this.x,this.y,this.x+10*cos(angle_convert(this.theta)),this.y+10*sin(angle_convert(this.theta)),this.x+dx+15*cos(angle_convert(this.theta)),this.y+dy+35*sin(angle_convert(this.theta)),this.x+dx+25*cos(angle_convert(this.theta)),this.y+dy+25*sin(angle_convert(this.theta)));
      let f = new Flower(this.x+dx+25*cos(angle_convert(this.theta)),this.y+dy+25*sin(angle_convert(this.theta)));
      f.display();
    }
  }
}
}

class Flower{
  
  constructor(xi, yi){
    this.num_petals = floor(random(5,7));
    this.x = xi; this.y = yi;
  }
  
  display(){
    push();
    noStroke();
    fill(255,255,255);
    let s = random(0.3,0.7);
    translate(this.x,this.y);
    scale(s);
    for (let i = 0; i < this.num_petals; i++){
      ellipse(7.5*cos(2*i/this.num_petals*PI),7.5*sin(2*i/this.num_petals*PI),10,10);
    }
    fill(200,20,100);
    ellipse(0,0,10,10);
    pop();
}
}

function branch_number(thickness){
  let det = random(0,thickness);
  let b = 7; let m = 64; let k = 2;
  return b - floor(log(m-det)/log(k));
}

function angle_prob(init_angle){
  let t = 1/45; let dt = t*(90-init_angle); let m = 2;
  return init_angle + random(-m+dt,m+dt)*random(-m,m);
}

function branch_thickness(num, angles, init_angle, init_thick){
  let fraction = [];
  let sumThick = 0; let half_angle = 45;
  for (let i = 0; i < num; i++){
    fraction[i] = half_angle/(half_angle+abs(90-angles[i])) + half_angle/(half_angle+abs(init_angle-angles[i]));
    sumThick += fraction[i];
  }
  let thick = [];
  for (let j = 0; j < num; j++){
    thick[j] = init_thick*sqrt(fraction[j]/sumThick);
  }
  return thick;
}

function angles_and_thicknesses(num, init_angle, init_thick){
  let theta = [];
  let results = [];
  let space_angle = 30;
  for (let i = 0; i < num; i++){
    theta[i] = angle_prob(init_angle + ((num-1)/2 - i) * space_angle);
  }
  let thick = branch_thickness(num,theta,init_angle,init_thick); 
  for (let j = 0; j < num; j++){
    results[2*j] = theta[j];
    results[2*j+1] = thick[j];
  }
  return results;
}

function angle_convert(angle){
  return -1*(PI/180)*angle;
}

      
    </script>
  </head>
  <body>
    <div id="myContainer" width="1200" height="900"></div>
  </body>
</html>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-inverse">
  <ul class="nav navbar-nav navbar-right">
    <li><a href="https://bitbucket.org/scwoolf/scwoolf/src/master/">Source</a></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  
  <div class="container-fluid">
    
    <div class="navbar-header">
      <%= link_to "Stuart Coulter Woolf", root_url, class: "navbar-brand" %>
    </div>
  
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              About <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Standards", about_standards_path %></li>
               <li class="divider"></li>
              <li><%= link_to "About Me", about_bio_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Courses <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Conceptual Physics", course_conceptual_physics_path %></li>
              <li><%= link_to "Algebra-based Physics", course_algebra_based_physics_path %></li>
               <li><%= link_to "Calculus-based Physics", course_calculus_based_physics_path %></li>
               <li class="divider"></li>
              <li><%= link_to "Calculus", course_calculus_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Computer Science", course_computer_science_path %></li>
            </ul>
          </li>
  <li><a href="mailto:coulter.woolf@gmail.com?Subject=Woolf">Contact</a></li>
    </ul>
  
  </div>
  
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stuart Coulter Woolf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>